CREATE TABLE statuses
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(32) NOT NULL UNIQUE
);

INSERT INTO statuses (status)
VALUES ('Друг'),
       ('Знакомый'),
       ('Сотрудник');
