CREATE TABLE contacts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(128) NOT NULL,
    last_name  VARCHAR(128) NOT NULL,
    birth_date DATE         NOT NULL,
    email      VARCHAR(255) UNIQUE,
    has_photo  BOOLEAN DEFAULT FALSE,
    photo_url  VARCHAR(512) NULL,
    status_id  BIGINT NULL,
    CONSTRAINT fk_contacts_status FOREIGN KEY (status_id) REFERENCES statuses (id) ON DELETE SET NULL
);

CREATE INDEX idx_contacts_status_id ON contacts (status_id);
